### ISSUE TITLE
App crashes after login on Android 6 device

### ISSUE THREAD

**Issue by kunisensei92** [grishka/Houseclub#45]
I changed **minSdkVersion** to **23**. App started on my device, but after I try to login app just crashes.

**Comment by kunisensei92** [comment]
> E/AndroidRuntime: FATAL EXCEPTION: ApiThread
    Process: me.grishka.houseclub, PID: 14007
    java.lang.NoSuchMethodError: No virtual method getLocales()Landroid/os/LocaleList; in class Landroid/content/res/Configuration; or its super classes (declaration of 'android.content.res.Configuration' appears in /system/framework/framework.jar)
        at me.grishka.houseclub.api.ClubhouseAPIController$RequestRunnable.run(ClubhouseAPIController.java:117)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at me.grishka.appkit.utils.WorkerThread.run(WorkerThread.java:54)
D/OpenGLRenderer: endAllStagingAnimators on 0x55c499f930 (InsetDrawable) with handle 0x55c4be88f0
E/WindowManager: android.view.WindowLeaked: Activity me.grishka.houseclub.MainActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{2761eae V.E...... R......D 0,0-1026,348} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:378)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
        at android.app.Dialog.show(Dialog.java:319)
        at me.grishka.houseclub.api.ClubhouseAPIRequest.exec(ClubhouseAPIRequest.java:48)
        at me.grishka.houseclub.fragments.LoginFragment.onNextClick(LoginFragment.java:92)
        at me.grishka.houseclub.fragments.LoginFragment.lambda$wpW1js_dSKMDJct6Yqa8Fcj23pc(LoginFragment.java)
        at me.grishka.houseclub.fragments.-$$Lambda$LoginFragment$wpW1js_dSKMDJct6Yqa8Fcj23pc.onClick(lambda)
        at android.view.View.performClick(View.java:5215)
        at android.view.View$PerformClick.run(View.java:21196)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5601)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
I/Process: Sending signal. PID: 14007 SIG: 9
