### ISSUE TITLE
Не проходит авторизацию по телефону

### ISSUE THREAD

**Issue by RFContracts** [grishka/Houseclub#6]
W/ClubhouseAPI: java.net.ConnectException: Failed to connect to www.clubhouseapi.com/2606:4700:10::6814:e02e:443
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at me.grishka.houseclub.api.ClubhouseAPIController$RequestRunnable.run(ClubhouseAPIController.java:134)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at me.grishka.appkit.utils.WorkerThread.run(WorkerThread.java:54)
     Caused by: java.net.ConnectException: failed to connect to www.clubhouseapi.com/2606:4700:10::6814:e02e (port 443) from /fec0::6dc6:8c0b:1d01:28a3 (port 50804) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:288)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
        at libcore.io.IoBridge.connect(IoBridge.java:135)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:71)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) 
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) 
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) 
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) 
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) 
        at okhttp3.RealCall.execute(RealCall.java:81) 
        at me.grishka.houseclub.api.ClubhouseAPIController$RequestRunnable.run(ClubhouseAPIController.java:134) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at me.grishka.appkit.utils.WorkerThread.run(WorkerThread.java:54) 
     Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:275)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:193) 
        at libcore.io.IoBridge.connect(IoBridge.java:135) 
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142) 
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390) 
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230) 
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212) 
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436) 
        at java.net.Socket.connect(Socket.java:621) 
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:71) 
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263) 
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) 
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) 
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) 
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) 
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) 
        at okhttp3.RealCall.execute(RealCall.java:81) 
        at me.grishka.houseclub.api.ClubhouseAPIController$RequestRunnable.run(ClubhouseAPIController.java:134) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at me.grishka.appkit.utils.WorkerThread.run(WorkerThread.java:54) 

Нажимаешь на Next, прелоадер и снова тоже самое.

**Comment by LionZXY** [comment]
На новой версии приложения воспроизводится?

**Comment by JanetkaNeskajy** [comment]
Не работает, открываю ввожу номер пароль из СМС и он вылетает назад к вводу номера и пароля.
